server:
  port: 8890

spring:
  application:
    name: admin-server
  mail:
    host: smtp.qq.com
    username: 1017306227@qq.com #自己的邮箱
    password: svgxmozpurtcbehc #邮箱的授权码
    properties:
      mail:
        smtp:
          auth: true   #安全认证(默认是true)
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          to: guanxb@163.com
          from: 1017306227@qq.com
        #钉钉群推送
        dingtalk:
          enabled: true
          webhook-token: https://oapi.dingtalk.com/robot/send?access_token=fde9cd362550fb085b89a2373e26fb4689eeb9e330e9be013a445d7bd8bca2fe

eureka:
  instance:
#    leaseRenewalIntervalInSeconds: 10
#    health-check-url-path: /actuator/health   #健康检查的地址
#    instance-id: admin-server #服务中心中该服务的注册名
#    prefer-ip-address: true #是否显示IP
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8880/eureka  #注册中心地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always