server:
  port: 8881

spring:
  application:
    name: server-hello
  #链路追踪配置
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/

#开放所有的endpoint供给admin监控用
management:
  endpoints:
    web:
      exposure:
        include: "*"