server:
  port: 8880

eureka:
#  instance:
#    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://148.70.126.138:${server.port}/eureka/

spring:
  application:
    name: eureka-server
