server:
  port: 8886

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kobeleehom/cloud-config  #https://github.com/forezp/SpringcloudConfig #
          searchPaths: demo
          username:
          password:
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/